
### Get a token
# databricks auth token --host https://dbc-c36d09ec-dbbe.cloud.databricks.com
curl \
  -X POST \
  -H "Authorization: Bearer $PASTE_YOUR_TOKEN" \
  -H "Content-Type: application/json" \
  -d@data.json \
  https://dbc-c36d09ec-dbbe.cloud.databricks.com/serving-endpoints/hotel-reservation-basic-model-serving-db/invocations

### From the command line
curl \
  -X POST \
  -H "Authorization: Bearer $(databricks auth token --host https://dbc-c36d09ec-dbbe.cloud.databricks.com | jq -r '.access_token')" \
  -H "Content-Type: application/json" \
  -d @data.json \
  https://dbc-c36d09ec-dbbe.cloud.databricks.com/serving-endpoints/hotel-reservation-basic-model-serving-db/invocations
